name: Social Readme

on:
  watch:
    types: started
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - name: Social Readme
        uses: Conquers/Conquers@master
        with:
          blog_rss_link: https://conquers.github.io/atom.xml
          blog_limit: 10
